#ifndef __UIKIT_THEME_DEFAULT__
#define __UIKIT_THEME_DEFAULT__

#include "../helpers/Colors.hpp"
#include "../fonts/Fonts.hpp"

#ifndef PADDING_NORMAL
#define PADDING_NORMAL 5
#endif

#ifndef SCREEN_BACKGROUND_COLOR
#define SCREEN_BACKGROUND_COLOR COLOR_WHITE
#endif

// TITLE BAR
#ifndef TITLE_BAR_HEIGHT
#define TITLE_BAR_HEIGHT 15
#endif
#ifndef TITLE_BAR_COLOR
#define TITLE_BAR_COLOR COLOR_PRIMARY
#endif
#ifndef TITLE_BAR_FONT_FAMILY
#define TITLE_BAR_FONT_FAMILY IBMPlexMono_Regular6pt8b
#endif
#ifndef TITLE_BAR_FONT_SIZE
#define TITLE_BAR_FONT_SIZE 1
#endif
#ifndef TITLE_BAR_FONT_COLOR
#define TITLE_BAR_FONT_COLOR COLOR_WHITE
#endif

#ifndef BUTTON_HEIGHT
#define BUTTON_HEIGHT 30
#endif

// BUTTON
#ifndef BUTTON_FONT_FAMILY
#define BUTTON_FONT_FAMILY FragmentMonoRegular20
#endif
#ifndef BUTTON_FONT_SIZE
#define BUTTON_FONT_SIZE 1
#endif
#ifndef BUTTON_BACKGROUND_COLOR_NORMAL
#define BUTTON_BACKGROUND_COLOR_NORMAL COLOR_PRIMARY
#endif
#ifndef BUTTON_BACKGROUND_COLOR_PRESSED
#define BUTTON_BACKGROUND_COLOR_PRESSED COLOR_PRIMARY_LIGHT
#endif
#ifndef BUTTON_TEXT_COLOR_NORMAL
#define BUTTON_TEXT_COLOR_NORMAL COLOR_WHITE
#endif
#ifndef BUTTON_TEXT_COLOR_PRESSED
#define BUTTON_TEXT_COLOR_PRESSED COLOR_PRIMARY
#endif

// TEXT BUTTON
#ifndef TEXT_BUTTON_COLOR_NORMAL
#define TEXT_BUTTON_COLOR_NORMAL COLOR_PRIMARY
#endif
#ifndef TEXT_BUTTON_COLOR_PRESSED
#define TEXT_BUTTON_COLOR_PRESSED COLOR_PRIMARY_LIGHT
#endif

// LIST
#ifndef LIST_BACKGROUND_COLOR
#define LIST_BACKGROUND_COLOR COLOR_PRIMARY_LIGHT
#endif
#ifndef LIST_SCROLL_BACKGROUND_COLOR
#define LIST_SCROLL_BACKGROUND_COLOR COLOR_LIGHT_GRAY
#endif
#ifndef LIST_ITEM_BACKGROUND_COLOR
#define LIST_ITEM_BACKGROUND_COLOR COLOR_PRIMARY_LIGHT
#endif
#ifndef LIST_ITEM_SELECTED_BACKGROUND_COLOR
#define LIST_ITEM_SELECTED_BACKGROUND_COLOR COLOR_COMPLEMENTARY_B
#endif
#ifndef LIST_ITEM_TEXT_COLOR
#define LIST_ITEM_TEXT_COLOR COLOR_DARK_GRAY
#endif
#ifndef LIST_ITEM_TEXT_SELECTED_COLOR
#define LIST_ITEM_TEXT_SELECTED_COLOR COLOR_BLACK
#endif

// TOGGLE_BUTTON
#ifndef TOGGLE_BUTTON_ON_BACKGROUND_COLOR
#define TOGGLE_BUTTON_ON_BACKGROUND_COLOR COLOR_COMPLEMENTARY_B
#endif
#ifndef TOGGLE_BUTTON_OFF_BACKGROUND_COLOR
#define TOGGLE_BUTTON_OFF_BACKGROUND_COLOR COLOR_SECONDARY
#endif
#ifndef TOGGLE_BUTTON_ON_TEXT_COLOR
#define TOGGLE_BUTTON_ON_TEXT_COLOR COLOR_BLACK
#endif
#ifndef TOGGLE_BUTTON_OFF_TEXT_COLOR
#define TOGGLE_BUTTON_OFF_TEXT_COLOR COLOR_BLACK
#endif

// PROGRESS_BAR
#ifndef PROGRESS_BAR_FONT_FAMILY
#define PROGRESS_BAR_FONT_FAMILY FragmentMonoRegular16
#endif
#ifndef PROGRESS_BAR_BORDER_COLOR
#define PROGRESS_BAR_BORDER_COLOR COLOR_COMPLEMENTARY_B
#endif
#ifndef PROGRESS_BAR_COLOR_A
#define PROGRESS_BAR_COLOR_A COLOR_COMPLEMENTARY_A
#endif
#ifndef PROGRESS_BAR_COLOR_B
#define PROGRESS_BAR_COLOR_B COLOR_COMPLEMENTARY_B
#endif
#ifndef PROGRESS_BAR_FONT_COLOR
#define PROGRESS_BAR_FONT_COLOR COLOR_BLACK
#endif

// LED
#ifndef LED_ON_COLOR
#define LED_ON_COLOR COLOR_GREEN
#endif
#ifndef LED_OFF_COLOR
#define LED_OFF_COLOR COLOR_GREEN
#endif

// LABEL
#ifndef LABEL_COLOR
#define LABEL_COLOR COLOR_DARK_GRAY
#endif
#ifndef LABEL_FONT_FAMILY
#define LABEL_FONT_FAMILY KdamThmorProRegular16
#endif

// ANALOG METER
#ifndef ANALOG_METER_FONT_FAMILY
#define ANALOG_METER_FONT_FAMILY KdamThmorProRegular14
#endif
#ifndef ANALOG_METER_FONT_SIZE
#define ANALOG_METER_FONT_SIZE 1
#endif
#ifndef ANALOG_METER_BORDER_COLOR
#define ANALOG_METER_BORDER_COLOR COLOR_BLACK
#endif
#ifndef ANALOG_METER_BACKGROUND_COLOR
#define ANALOG_METER_BACKGROUND_COLOR COLOR_WHITE
#endif
#ifndef ANALOG_METER_FONT_COLOR
#define ANALOG_METER_FONT_COLOR COLOR_BLACK
#endif
#ifndef ANALOG_METER_ARC_MARK_COLOR
#define ANALOG_METER_ARC_MARK_COLOR COLOR_BLACK
#endif
#ifndef ANALOG_METER_INDICATOR_COLOR
#define ANALOG_METER_INDICATOR_COLOR COLOR_BLACK
#endif
#ifndef ANALOG_METER_UNITS_FONT_FAMILY
#define ANALOG_METER_UNITS_FONT_FAMILY KdamThmorProRegular14
#endif
#ifndef ANALOG_METER_TITLE_FONT_FAMILY
#define ANALOG_METER_TITLE_FONT_FAMILY OpenSansRegular14
#endif
#ifndef ANALOG_METER_UNITS_FONT_SIZE
#define ANALOG_METER_UNITS_FONT_SIZE 1
#endif
#ifndef ANALOG_METER_UNITS_FONT_COLOR
#define ANALOG_METER_UNITS_FONT_COLOR COLOR_BLACK
#endif
#ifndef ANALOG_METER_TITLE_FONT_COLOR
#define ANALOG_METER_TITLE_FONT_COLOR COLOR_PRIMARY
#endif

#endif